CREATE TABLE `player_bonus_stats` (
	`race` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`str` SMALLINT(5) UNSIGNED NULL DEFAULT '0',
	`agi` SMALLINT(5) UNSIGNED NULL DEFAULT '0',
	`inte` SMALLINT(5) UNSIGNED NULL DEFAULT '0',
	`sta` SMALLINT(5) UNSIGNED NULL DEFAULT '0',
	`spi` SMALLINT(5) UNSIGNED NULL DEFAULT '0',
	PRIMARY KEY (`race`, `class`, `level`)
)
ENGINE=InnoDB DEFAULT CHARSET=latin1;